resources:
- repo: self

pool:
  vmImage: 'vs2017-win2016'

# queue:
#   name: Hosted VS2017
#   demands: 
#   - visualstudio

steps:
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'
  inputs:
    vsVersion: 15.0
    platform: x64
    configuration: debug
    msbuildArchitecture: x64
